export * from './admin/MicrosoftLoginLocators';
export * from './admin/LoginPageLocators';
export * from './admin/AdminPageLocators';
export * from './admin/UserGroupLocators';    
export * from './admin/CommonLocators';
export * from './admin/FaqsPageLocators';
export * from './admin/ContentPageLocators';
export * from './admin/HealthcarePageLocators';
export * from './admin/DoctorsPageLocators';
export * from './admin/SchedulePageLocators';
export * from './admin/LocationPageLocators'